### ISSUE TITLE
Not everybody is named Kamron

### ISSUE THREAD

**Issue by mjkaufer** [KamronSoldozy/File-Exploring#2]
https://github.com/KamronSoldozy/File-Exploring/blob/master/FileSearch.java#L18

Give users the option to customize their root folder. Unfortunately, not everybody is blessed with a name as majestic as Kamron.

**Comment by KamronSoldozy** [comment]
you can customize your root folder, you have to type it out
my name is the example (and for me so i can just copy and paste ;) )
